// Generated by gencpp from file autominy_msgs/Obstacle.msg
// DO NOT EDIT!


#ifndef AUTOMINY_MSGS_MESSAGE_OBSTACLE_H
#define AUTOMINY_MSGS_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/Odometry.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>

namespace autominy_msgs
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : header()
    , object_frame_id()
    , object_id(0)
    , age()
    , prediction_age()
    , odom()
    , size()
    , contour_points()
    , classification(0)
    , classification_age()
    , classification_certainty(0.0)  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_frame_id(_alloc)
    , object_id(0)
    , age()
    , prediction_age()
    , odom(_alloc)
    , size(_alloc)
    , contour_points(_alloc)
    , classification(0)
    , classification_age()
    , classification_certainty(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_frame_id_type;
  _object_frame_id_type object_frame_id;

   typedef uint16_t _object_id_type;
  _object_id_type object_id;

   typedef ros::Duration _age_type;
  _age_type age;

   typedef ros::Duration _prediction_age_type;
  _prediction_age_type prediction_age;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _odom_type;
  _odom_type odom;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _contour_points_type;
  _contour_points_type contour_points;

   typedef uint16_t _classification_type;
  _classification_type classification;

   typedef ros::Duration _classification_age_type;
  _classification_age_type classification_age;

   typedef double _classification_certainty_type;
  _classification_certainty_type classification_certainty;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNCLASSIFIED)
  #undef UNCLASSIFIED
#endif
#if defined(_WIN32) && defined(UNKNOWN_SMALL)
  #undef UNKNOWN_SMALL
#endif
#if defined(_WIN32) && defined(UNKNOWN_BIG)
  #undef UNKNOWN_BIG
#endif
#if defined(_WIN32) && defined(PEDESTRIAN)
  #undef PEDESTRIAN
#endif
#if defined(_WIN32) && defined(BIKE)
  #undef BIKE
#endif
#if defined(_WIN32) && defined(CAR)
  #undef CAR
#endif
#if defined(_WIN32) && defined(TRUCK)
  #undef TRUCK
#endif

  enum {
    UNCLASSIFIED = 0u,
    UNKNOWN_SMALL = 1u,
    UNKNOWN_BIG = 2u,
    PEDESTRIAN = 3u,
    BIKE = 4u,
    CAR = 5u,
    TRUCK = 6u,
  };


  typedef boost::shared_ptr< ::autominy_msgs::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autominy_msgs::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::autominy_msgs::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::autominy_msgs::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::autominy_msgs::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autominy_msgs::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autominy_msgs::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autominy_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::autominy_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_frame_id == rhs.object_frame_id &&
    lhs.object_id == rhs.object_id &&
    lhs.age == rhs.age &&
    lhs.prediction_age == rhs.prediction_age &&
    lhs.odom == rhs.odom &&
    lhs.size == rhs.size &&
    lhs.contour_points == rhs.contour_points &&
    lhs.classification == rhs.classification &&
    lhs.classification_age == rhs.classification_age &&
    lhs.classification_certainty == rhs.classification_certainty;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autominy_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::autominy_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autominy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autominy_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autominy_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autominy_msgs::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autominy_msgs::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autominy_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autominy_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autominy_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56ed5dd3c8412ae50b6a996467672cf4";
  }

  static const char* value(const ::autominy_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56ed5dd3c8412ae5ULL;
  static const uint64_t static_value2 = 0x0b6a996467672cf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::autominy_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autominy_msgs/Obstacle";
  }

  static const char* value(const ::autominy_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autominy_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Detected or simulated object\n"
"################################################################################\n"
"\n"
"# Header\n"
"# header.frame_id defines reference frame\n"
"Header header\n"
"\n"
"# Object frame (analogous to child_frame_id in nav_msgs/Odometry)\n"
"string object_frame_id\n"
"\n"
"\n"
"# ID for tracking\n"
"uint16 object_id\n"
"\n"
"# duration this object has been tracked for\n"
"duration age\n"
"\n"
"# duration since last update/confirmation by measurement\n"
"# (set to 0 as soon as a measurement update is available)\n"
"duration prediction_age\n"
"\n"
"\n"
"# odometry of the object (position, orientation, linear and angular velocities)\n"
"# odom.header.frame_id is header.frame_id\n"
"# child_frame_id is object_frame_id\n"
"nav_msgs/Odometry odom\n"
"\n"
"# maximal size of the object (x,y,z) or (depth, width, height) [m]\n"
"# relative to the object frame, i.e. the orientation of the object is taken into account\n"
"geometry_msgs/Vector3 size\n"
"\n"
"\n"
"# The contour points of the object [m]\n"
"geometry_msgs/Point[] contour_points\n"
"\n"
"\n"
"# definition of most likely class of this object:\n"
"#   0: unclassified\n"
"#   1: unknown small\n"
"#   2: unknown big\n"
"#   3: pedestrian\n"
"#   4: bike\n"
"#   5: car\n"
"#   6: truck\n"
"uint16 UNCLASSIFIED    = 0\n"
"uint16 UNKNOWN_SMALL   = 1\n"
"uint16 UNKNOWN_BIG     = 2\n"
"uint16 PEDESTRIAN      = 3\n"
"uint16 BIKE            = 4\n"
"uint16 CAR             = 5\n"
"uint16 TRUCK           = 6\n"
"\n"
"# most likely class of this object\n"
"uint16 classification\n"
"\n"
"# duration this object has been classified as current class\n"
"duration classification_age\n"
"\n"
"# The higher this value the more reliable the assigned object class [0,1]\n"
"float64 classification_certainty\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::autominy_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autominy_msgs::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_frame_id);
      stream.next(m.object_id);
      stream.next(m.age);
      stream.next(m.prediction_age);
      stream.next(m.odom);
      stream.next(m.size);
      stream.next(m.contour_points);
      stream.next(m.classification);
      stream.next(m.classification_age);
      stream.next(m.classification_certainty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autominy_msgs::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autominy_msgs::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_frame_id);
    s << indent << "object_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object_id);
    s << indent << "age: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.age);
    s << indent << "prediction_age: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.prediction_age);
    s << indent << "odom: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.odom);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "contour_points[]" << std::endl;
    for (size_t i = 0; i < v.contour_points.size(); ++i)
    {
      s << indent << "  contour_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.contour_points[i]);
    }
    s << indent << "classification: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.classification);
    s << indent << "classification_age: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.classification_age);
    s << indent << "classification_certainty: ";
    Printer<double>::stream(s, indent + "  ", v.classification_certainty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMINY_MSGS_MESSAGE_OBSTACLE_H
