// Generated by gencpp from file autominy_msgs/Speed.msg
// DO NOT EDIT!


#ifndef AUTOMINY_MSGS_MESSAGE_SPEED_H
#define AUTOMINY_MSGS_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autominy_msgs
{
template <class ContainerAllocator>
struct Speed_
{
  typedef Speed_<ContainerAllocator> Type;

  Speed_()
    : header()
    , value(0.0)  {
    }
  Speed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::autominy_msgs::Speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autominy_msgs::Speed_<ContainerAllocator> const> ConstPtr;

}; // struct Speed_

typedef ::autominy_msgs::Speed_<std::allocator<void> > Speed;

typedef boost::shared_ptr< ::autominy_msgs::Speed > SpeedPtr;
typedef boost::shared_ptr< ::autominy_msgs::Speed const> SpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autominy_msgs::Speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autominy_msgs::Speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autominy_msgs::Speed_<ContainerAllocator1> & lhs, const ::autominy_msgs::Speed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autominy_msgs::Speed_<ContainerAllocator1> & lhs, const ::autominy_msgs::Speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autominy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autominy_msgs::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autominy_msgs::Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autominy_msgs::Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autominy_msgs::Speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autominy_msgs::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autominy_msgs::Speed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autominy_msgs::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d053817de0764f9ee90dbc89c4cdd751";
  }

  static const char* value(const ::autominy_msgs::Speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd053817de0764f9eULL;
  static const uint64_t static_value2 = 0xe90dbc89c4cdd751ULL;
};

template<class ContainerAllocator>
struct DataType< ::autominy_msgs::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autominy_msgs/Speed";
  }

  static const char* value(const ::autominy_msgs::Speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autominy_msgs::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# speed [m/s]\n"
"float64 value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::autominy_msgs::Speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autominy_msgs::Speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autominy_msgs::Speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autominy_msgs::Speed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMINY_MSGS_MESSAGE_SPEED_H
