# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bno055_usb_stick_msgs/CalibrationStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CalibrationStatus(genpy.Message):
  _md5sum = "dcc2b46dfebad9476df3c38a333f4515"
  _type = "bno055_usb_stick_msgs/CalibrationStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 3 indicates fully calibrated; 0 indicates not calibrated

uint16 system
uint16 gyroscope
uint16 accelerometer
uint16 magnetometer"""
  __slots__ = ['system','gyroscope','accelerometer','magnetometer']
  _slot_types = ['uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       system,gyroscope,accelerometer,magnetometer

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CalibrationStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.system is None:
        self.system = 0
      if self.gyroscope is None:
        self.gyroscope = 0
      if self.accelerometer is None:
        self.accelerometer = 0
      if self.magnetometer is None:
        self.magnetometer = 0
    else:
      self.system = 0
      self.gyroscope = 0
      self.accelerometer = 0
      self.magnetometer = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.system, _x.gyroscope, _x.accelerometer, _x.magnetometer))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.system, _x.gyroscope, _x.accelerometer, _x.magnetometer,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.system, _x.gyroscope, _x.accelerometer, _x.magnetometer))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.system, _x.gyroscope, _x.accelerometer, _x.magnetometer,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
